title: TheNerdOne Blog
description: > # this means to ignore newlines until "baseurl:"
  Hacking content, CTF/Exercises writeups, and some personal posts to share some of my ideas.
permalink: ':/'
baseurl: "/index" # the subpath of your site, e.g. /blog
url: "https://thenerdone9.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "https://twitter.com/thenerdone9"

# Author Settings
author: Diogo Gomes
author-img: thenerdone.jpg # add your photo
about-author: Ethical Hacker | MSc Cybersecurity Student at FCUP | Security Consultant | OSCP | CTF Player
social-twitter: "https://twitter.com/thenerdone9"
social-facebook: "https://www.hackthebox.eu/profile/57120"
social-github: thenerdone9 # add your Github handle
social-linkedin: "https://pt.linkedin.com/in/diogo-salvador"
social-email: salvador.diogogomes@gmail.com

# Disqus
discus-identifier: # Disqus App

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
